name: cherrytree
adopt-info: com.giuspen.cherrytree
summary: Hierarchical note taking application
description: |
  A hierarchical note taking application, featuring rich text and syntax highlighting, storing data in a single XML or SQLite file. The project home page is giuspen.com/cherrytree.

grade: stable
confinement: strict
base: core20

slots:
  cherrytree:
    interface: dbus
    bus: session
    name: com.giuspen.CherryTreeService

apps:
  cherrytree:
    command: usr/bin/cherrytree
    extensions: [ gnome-3-38 ]
    plugs:
      - home
      - removable-media
      - network
    desktop: share/applications/cherrytree.desktop
    common-id: com.giuspen.cherrytree
    environment:
      PATH: $SNAP/usr/lib/p7zip:$PATH
      GTK_DATA_PREFIX: $SNAP
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS

parts:
  uchardet:
    source: https://github.com/freedesktop/uchardet.git
    source-tag: 'v0.0.7'
    plugin: cmake
    

  cherrytree:
    after: [ uchardet ]
    source: .
    source-type: git
    source-tag: '0.99.36'
    plugin: cmake
    build-snaps: [ gnome-3-38-2004-sdk/latest/candidate ]
    override-build: |
      set -eux
      cd $SNAPCRAFT_PART_SRC
      ./build.sh
      #snapcraftctl build
    #  cd pygtk2
    #  python2.7 setup.py install --prefix=$SNAPCRAFT_PART_INSTALL/usr -f 
    #  sed -i 's|^Icon=.*|Icon=${SNAP}/meta/gui/cherrytree.png|' linux/cherrytree.desktop
    #  sed -i '1s|.*|#!/usr/bin/env python2.7|' $SNAPCRAFT_PART_INSTALL/usr/bin/cherrytree
    #  sed -i 's|VERSION = "0.39.4"|VERSION = "0.99.35"|' $SNAPCRAFT_PART_INSTALL/usr/share/cherrytree/modules/cons.py
    #  mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
    #  cp glade/cherrytree.png $SNAPCRAFT_PART_INSTALL/meta/gui/
    #  mkdir -p $SNAPCRAFT_PART_INSTALL/share/applications/
    #  cp linux/cherrytree.desktop $SNAPCRAFT_PART_INSTALL/share/applications/
    build-packages:
      - build-essential
      - cmake
      - desktop-file-utils
      - gettext
      - libcurl4-openssl-dev
      - libfmt-dev
      - libgtksourceviewmm-3.0-dev
      - libsigc++-2.0-dev
      - libspdlog-dev
      - libgspell-1-dev
      - libsqlite3-dev
      - libxml++2.6-dev
      - ninja-build
    #stage-packages:
      #- python2.7-minimal
      #- python-gtk2
      #- python-gtksourceview2
      #- p7zip-full
      #- python-dbus
      #- python-chardet
      #- python3-urllib3
    prime:
      - -usr/bin/7za
