name: cherrytree
adopt-info: com.giuspen.cherrytree
summary: Hierarchical note taking application
description: |
  A hierarchical note taking application, featuring rich text and syntax highlighting, storing data in a single XML or SQLite file. The project home page is giuspen.com/cherrytree.

grade: stable
confinement: strict
base: core20

slots:
  cherrytree:
    interface: dbus
    bus: session
    name: com.giuspen.CherryTreeService

apps:
  cherrytree:
    command: usr/bin/cherrytree
    extensions: [ gnome-3-38 ]
    plugs:
      - home
      - removable-media
      - network
    desktop: share/applications/cherrytree.desktop
    common-id: com.giuspen.cherrytree
    environment:
      PATH: $SNAP/usr/lib/p7zip:$PATH
      GTK_DATA_PREFIX: $SNAP
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS

parts:
  #uchardet:
  #  source: https://github.com/freedesktop/uchardet.git
  #  source-tag: 'v0.0.7'
  #  plugin: cmake
  #  cmake-parameters:
  #    - -DCMAKE_INSTALL_PREFIX=/usr

  buildenv:
    plugin: nil
    build-environment: &buildenv
      - ACLOCAL_PATH: $SNAPCRAFT_STAGE/usr/share/aclocal
      - XDG_DATA_DIRS: $SNAPCRAFT_STAGE/usr/share:/usr/share:$XDG_DATA_DIRS
      - LD_LIBRARY_PATH: $SNAPCRAFT_STAGE/usr/lib/vala-0.48:$SNAPCRAFT_STAGE/usr/lib:$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH
      - GDK_PIXBUF_MODULE_FILE: $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/2.10.0/loaders.cache
      - PKG_CONFIG_PATH: $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig:$SNAPCRAFT_STAGE/usr/lib/pkgconfig:$SNAPCRAFT_STAGE/usr/share/pkgconfig:$PKG_CONFIG_PATH

  glib:
    after: [ buildenv ]
    source: https://download-fallback.gnome.org/sources/glib/2.70/glib-2.70.0.tar.xz
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    build-environment: *buildenv
    build-environment:
      - CFLAGS: -Wno-nonnull
    override-build: |
      set -eux
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/glib-2.0/
      cp $SNAPCRAFT_PART_INSTALL/usr/bin/{gio-querymodules,glib-compile-schemas} $SNAPCRAFT_PART_INSTALL/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/glib-2.0/
    build-packages:
      - pkg-config
      - libmount-dev
      - gcc
      - g++
      - clang
      - libffi-dev

  wayland:
    after: [ glib ]
    source: https://gitlab.freedesktop.org/wayland/wayland.git
    source-tag: '1.19.92'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    #  - --disable-documentation
    build-environment: *buildenv
    build-environment:
      - LD_LIBRARY_PATH: $SNAPCRAFT_STAGE/usr/lib/vala-0.48:$SNAPCRAFT_STAGE/usr/lib:$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      - PKG_CONFIG_PATH: $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig:$SNAPCRAFT_STAGE/usr/lib/pkgconfig:$SNAPCRAFT_STAGE/usr/share/pkgconfig
    build-packages:
      - xmlto

  wayland-protocols:
    after: [ wayland ]
    source: https://gitlab.freedesktop.org/wayland/wayland-protocols.git
    source-tag: '1.23'
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters: [ --prefix=/usr ]
    build-environment: *buildenv

  gtk4:
    after: [ wayland-protocols ]
    source: https://download-fallback.gnome.org/sources/gtk/4.4/gtk-4.4.0.tar.xz
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      #- -Dbroadway_backend=true
      #- -Dx11_backend=true
      #- -Dwayland_backend=true
      #- -Dwin32_backend=false
      - -Dmacos-backend=false
      - -Dintrospection=enabled
      - -Dgtk_doc=false
      - -Ddemos=false
      - -Dbuild-examples=false
      - -Dmedia-gstreamer=disabled
      - -Dinstall-tests=false
    #build-environment:
    #  - LD_LIBRARY_PATH: $SNAPCRAFT_STAGE/usr/lib/glib-2.0:$SNAPCRAFT_STAGE/usr/lib:$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
    #  - PKG_CONFIG_PATH: $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig:$SNAPCRAFT_STAGE/usr/lib/pkgconfig:$SNAPCRAFT_STAGE/usr/share/pkgconfig
    build-environment: *buildenv
    override-pull: |
      snapcraftctl pull
      sed -i.bak -e 's|error=redundant|redundant|g' meson.build
    organize:
      usr/lib/gtk-4.0: usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-4.0
      #usr/bin/gtk-query-immodules-3.0: usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgtk-3-0/gtk-query-immodules-3.0
    build-packages:
      - libcairo2-dev
      - libgraphene-1.0-dev
      - libwayland-cursor++0

  mm-common:
    after: [ gtk4 ]
    source: https://gitlab.gnome.org/GNOME/mm-common.git
    source-tag: '1.0.3'
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Duse-network=true
    override-build: |
      set -eux
      snapcraftctl build
    build-packages:
      - wget

  gobject-introspection:
    after: [ mm-common ]
    source: https://download-fallback.gnome.org/sources/gobject-introspection/1.70/gobject-introspection-1.70.0.tar.xz
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    build-environment:
      - LD_LIBRARY_PATH: $SNAPCRAFT_STAGE/usr/lib/vala-0.48:$SNAPCRAFT_STAGE/usr/lib:$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      - PKG_CONFIG_PATH: $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig:$SNAPCRAFT_STAGE/usr/lib/pkgconfig:$SNAPCRAFT_STAGE/usr/share/pkgconfig
    override-build: |
      set -eux
      snapcraftctl build
      SCANNER=$SNAPCRAFT_PART_INSTALL/usr/bin/g-ir-scanner
      sed -i 's#/usr/lib#$SNAPCRAFT_STAGE/usr/lib#g' $SCANNER
      sed -i 's#/usr/share#$SNAPCRAFT_STAGE/usr/share#g' $SCANNER
    build-packages:
      - python3-dev
      - bison
      - flex


  gtkmm:
    after: [ gobject-introspection ]
    source: https://download.gnome.org/sources/gtkmm/4.0/gtkmm-4.0.0.tar.xz
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Dmaintainer-mode=true
      - -Dbuild-documentation=false
      - -Dbuild-demos=false
    build-environment:
      - ACLOCAL_PATH: $SNAPCRAFT_STAGE/usr/share/aclocal
      - XDG_DATA_DIRS: $SNAPCRAFT_STAGE/usr/share:/usr/share:$XDG_DATA_DIRS
      - LD_LIBRARY_PATH: $SNAPCRAFT_STAGE/usr/lib/vala-0.48:$SNAPCRAFT_STAGE/usr/lib:$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/$LD_LIBRARY_PATH
      - GDK_PIXBUF_MODULE_FILE: $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/2.10.0/loaders.cache
      - M4PATH: $SNAPCRAFT_STAGE/usr/lib/glibmm-2.4/proc/m4
    override-build: |
      set -eux
      mkdir -p ../src/untracked/build_scripts/
      cp -p $SNAPCRAFT_STAGE/usr/share/mm-common/build/generate-binding.py ../src/untracked/build_scripts/
      snapcraftctl build
    build-packages:
      - libgstreamer-plugins-bad1.0-dev
      - doxygen
      - graphviz
      - xsltproc


  gtksourceviewmm:
    after: [ gtkmm ]
    source: https://github.com/GNOME/gtksourceviewmm.git
    plugin: autotools
    build-snaps: [ gnome-3-38-2004-sdk/latest/candidate ]
    override-build: |
      set -eux
      # Make sure all of the *.am files from mm-common are found
      cp $SNAPCRAFT_STAGE/usr/share/mm-common/build/*.am /usr/share/mm-common/build/
      cp $SNAPCRAFT_STAGE/usr/share/mm-common/doctool/* /usr/share/mm-common/doctool/
      snapcraftctl build


  cherrytree:
    after:
      #- uchardet
      - gtksourceviewmm
      - gtkmm
    source: .
    source-type: git
    source-tag: '0.99.43'
    plugin: cmake
    build-snaps: [ gnome-3-38-2004-sdk/latest/candidate ]
    #build-environment:
      #- LD_LIBRARY_PATH=$SNAPCRAFT_STAGE/usr/local/include:$LD_LIBRARY_PATH
      #- PATH: $SNAPCRAFT_STAGE/usr/local/include:$PATH
    override-build: |
      set -eux
      cd $SNAPCRAFT_PART_SRC
      ./build.sh
      #snapcraftctl build
    #  cd pygtk2
    #  python2.7 setup.py install --prefix=$SNAPCRAFT_PART_INSTALL/usr -f 
    #  sed -i 's|^Icon=.*|Icon=${SNAP}/meta/gui/cherrytree.png|' linux/cherrytree.desktop
    #  sed -i '1s|.*|#!/usr/bin/env python2.7|' $SNAPCRAFT_PART_INSTALL/usr/bin/cherrytree
    #  sed -i 's|VERSION = "0.39.4"|VERSION = "0.99.35"|' $SNAPCRAFT_PART_INSTALL/usr/share/cherrytree/modules/cons.py
    #  mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
    #  cp glade/cherrytree.png $SNAPCRAFT_PART_INSTALL/meta/gui/
    #  mkdir -p $SNAPCRAFT_PART_INSTALL/share/applications/
    #  cp linux/cherrytree.desktop $SNAPCRAFT_PART_INSTALL/share/applications/
    build-packages:
      - build-essential
      - cmake
      - desktop-file-utils
      - gettext
      - libcurl4-openssl-dev
      - libfmt-dev
      - libsigc++-2.0-dev
      - libspdlog-dev
      - libgspell-1-dev
      - libsqlite3-dev
      - libuchardet0
      - libuchardet-dev
      - libxml++2.6-dev
      - ninja-build
    #stage-packages:
      #- python2.7-minimal
      #- python-gtk2
      #- python-gtksourceview2
      #- p7zip-full
      #- python-dbus
      #- python-chardet
      #- python3-urllib3
    prime:
      - -usr/bin/7za
