name: cherrytree
version: 0.99.24
summary: Hierarchical note taking application
description: |
  A hierarchical note taking application, featuring rich text and syntax highlighting, storing data in a single XML or SQLite file. The project home page is giuspen.com/cherrytree.

grade: stable
confinement: strict
base: core18

slots:
  cherrytree:
    interface: dbus
    bus: session
    name: com.giuspen.CherryTreeService

apps:
  cherrytree:
    command: usr/bin/cherrytree
    extensions: [gnome-3-34]
    plugs:
      - home
      - removable-media
      - network
    desktop: share/applications/cherrytree.desktop
    common-id: com.giuspen.cherrytree
    environment:
      PATH: $SNAP/usr/lib/p7zip:$PATH
      GTK_PATH: $SNAP/lib/gtk-2.0
      GTK_DATA_PREFIX: $SNAP
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS

parts:

  desktop-patch:
    source: snap/local/patches
    source-type: local
    plugin: dump
    prime: [-* ]

  cherrytree:
    after: [ desktop-patch ]
    source: .
    source-tag: '0.99.24'
    plugin: cmake
    override-build: |
      set -x
      snapcraftctl build
      #cd pygtk2
      #python2.7 setup.py install --prefix=$SNAPCRAFT_PART_INSTALL/usr -f 
      sed -i 's|^Icon=.*|Icon=${SNAP}/meta/gui/cherrytree.png|' linux/cherrytree.desktop
      sed -i '1s|.*|#!/usr/bin/env python2.7|' $SNAPCRAFT_PART_INSTALL/usr/bin/cherrytree
      sed -i 's|VERSION = "0.39.4"|VERSION = "0.99.24"|' $SNAPCRAFT_PART_INSTALL/usr/share/cherrytree/modules/cons.py
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp glade/cherrytree.png $SNAPCRAFT_PART_INSTALL/meta/gui/
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/applications/
      cp linux/cherrytree.desktop $SNAPCRAFT_PART_INSTALL/share/applications/
    build-packages:
      #- python2.7
      - gettext
      - desktop-file-utils
      - libsigc++-2.0-dev
    stage-packages:
      #- python2.7-minimal
      #- python-gtk2
      #- python-gtksourceview2
      - p7zip-full
      - python-dbus
      - python-enchant
      - python-chardet
      - python3-urllib3
    prime:
      - -usr/bin/7za
